'''
This section will have you make the UI and Foreground/Background mask creation

You may use ANY tools to complete this section (but not the other) -- 
though you must label any lines of code generated by an LLM or copied from a friend
'''
from PIL import Image
import numpy as np
import cv2

def dir_to_img(dir='test_images/easy.jpg'): #Used LLM
    '''
    Takes a string which is a directory to a jpg or png image. Use whatever library you'd like to 
    convert that image into a 3d numpy array (3, height, width)
    '''
    try:
        # Open the image and ensure it is in RGB format (drops alpha channels if png)
        img = Image.open(dir).convert('RGB')
        
        # Convert the PIL image to a NumPy array
        # This creates an array with shape (height, width, 3)
        img_matrix = np.array(img)
        
        # Transpose the matrix to match the required (3, height, width) shape.
        # Original axes: 0=height, 1=width, 2=channels
        # New axes: 2=channels, 0=height, 1=width
        formatted_matrix = np.transpose(img_matrix, (2, 0, 1))
        
        return formatted_matrix
        
    except FileNotFoundError:
        print(f"Error: The image at {dir} could not be found.")
        return None
    except Exception as e:
        print(f"An error occurred while loading the image: {e}")
        return None


def display_img(img):
    '''
    Given a 3d matrix (a numpy matrix (3, height, width)) display the image
    '''
    # 1. Reformat the image for OpenCV display
    # Transpose from (3, H, W) -> (H, W, 3)
    img_display = np.transpose(img, (1, 2, 0))
    
    # Ensure the image is a uint8 type (0-255) for OpenCV to render it correctly
    if img_display.dtype != np.uint8:
        img_display = img_display.astype(np.uint8)
        
    # Convert RGB to BGR (OpenCV's default color space)
    img_bgr = cv2.cvtColor(img_display, cv2.COLOR_RGB2BGR)
    
    # 2. Setup the empty binary mask
    height, width = img_bgr.shape[:2]
    mask = np.zeros((height, width), dtype=np.uint8)
    
    # State variables for the drawing logic
    drawing = False
    brush_size = 5  # Adjust this for a thicker or thinner brush

    # 3. Define the mouse callback function
    def draw_scribble(event, x, y, flags, param):
        nonlocal drawing, mask, img_bgr
        
        # When the left mouse button is pressed down, start drawing
        if event == cv2.EVENT_LBUTTONDOWN:
            drawing = True
            cv2.circle(mask, (x, y), brush_size, 1, -1) # Write 1s to the mask
            cv2.circle(img_bgr, (x, y), brush_size, (0, 0, 255), -1) # Draw red on screen
            
        # When the mouse moves while the button is held down
        elif event == cv2.EVENT_MOUSEMOVE:
            if drawing:
                cv2.circle(mask, (x, y), brush_size, 1, -1)
                cv2.circle(img_bgr, (x, y), brush_size, (0, 0, 255), -1)
                
        # When the left mouse button is released, stop drawing
        elif event == cv2.EVENT_LBUTTONUP:
            drawing = False

    # 4. Create the UI Window
    window_name = 'Draw Scribbles (Press ESC to finish)'
    cv2.namedWindow(window_name)
    cv2.setMouseCallback(window_name, draw_scribble)

    print("Click and drag to draw. Press the 'ESC' key when finished.")

    # 5. Run the display loop
    while True:
        cv2.imshow(window_name, img_bgr)
        # Wait for 1ms and check if the user pressed the ESC key (ASCII 27)
        if cv2.waitKey(1) & 0xFF == 27: 
            break

    cv2.destroyAllWindows()
    
    return mask

def User_interface(img):
    '''
    Given an image (3d numpy matrix (3, height, width)), must create a user interface which displays the image and
    allows a user to mark some pixels of it. This should return a binary matrix where
    a 1 represents a position which was marked and 0s everywhere else
    '''

    return

def apply_masks(img, mask):
    '''
    Docstring for apply_masks
    
    :param img: An image, a 3d numpy matrix containing the RGB values of each pixel of an image (3, height, width)
    :param mask: A binary (only 0 or 1) 2d numpy matrix. The 1s represent pixels which should be kept, the others should be discarded (made black) 
    '''

    # TODO -- needed for your written report

    return